public with sharing class BotDataConstants 
{
	public static final string Message_Todays_Activity = 'Todays_Activity';
    public static final string Message_Auth_Successful = 'Auth_Successful';
    public static final string Message_Auth_Failed = 'Auth_Failed';
    
    public static final string Message_Deploy_Successful = 'Deploy_Successful';
    public static final string Message_Deploy_Failed = 'Deploy_Failed';
    
    public static final string Type_Fitbit = 'Fitbit';
}